# Generated by Django 4.1.4 on 2022-12-20 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=10, null=True, unique=True)),
                ("payroll_id", models.CharField(max_length=10, null=True, unique=True)),
                ("photo", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="personal email",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "job_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DSO", "Distribution Service Officer"),
                            ("P&T", "Protection & Testing Officer"),
                            ("PLT", "Power Line Technician"),
                            ("PST", "Power Service Technician"),
                            ("PCT", "Power Cable Technician"),
                            ("NP", "Network Planner"),
                            ("OME", "Maintenance Engineer"),
                            ("DA", "Data Analyst"),
                        ],
                        max_length=3,
                        verbose_name="job role",
                    ),
                ),
                (
                    "other_job_role",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="other job role"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("CTO", "Chief Technical Officer"),
                            ("HOU", "Head of Unit"),
                            ("TMG", "Technical Manager"),
                            ("TS", "Technical Supervisor"),
                            ("TL", "Team Lead"),
                            ("SUP", "Supervisor"),
                            ("TM", "Team Member"),
                            ("TR", "Trainee"),
                        ],
                        default="TM",
                        max_length=3,
                        verbose_name="designation",
                    ),
                ),
                (
                    "other_designation",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="other designation"
                    ),
                ),
                (
                    "area_office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.areaoffice",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.servicecenter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
