# Generated by Django 4.1.6 on 2023-02-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_dso",
            field=models.BooleanField(default=False, verbose_name="is dso?"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_hq_staff",
            field=models.BooleanField(
                default=False, verbose_name="is head office staff?"
            ),
        ),
    ]
