# Generated by Django 4.1.4 on 2022-12-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "name already assigned to another area office"
                        },
                        max_length=25,
                        unique=True,
                        verbose_name="area office",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        error_messages={
                            "unique": "code already assigned to another area office"
                        },
                        help_text="required a 3 characters uniqe code",
                        max_length=3,
                        unique=True,
                        verbose_name="area office code",
                    ),
                ),
                (
                    "technical_manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "name already assigned to another area office"
                        },
                        max_length=25,
                        unique=True,
                        verbose_name="service center",
                    ),
                ),
                (
                    "area_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.areaoffice",
                    ),
                ),
                (
                    "technical_supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
