# Generated by Django 4.1.4 on 2022-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1, unique=True, verbose_name="feeder band"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="band description",
                    ),
                ),
                (
                    "hos",
                    models.PositiveSmallIntegerField(verbose_name="hours of supply"),
                ),
                ("tariff", models.FloatField(verbose_name="tariff rate")),
            ],
        ),
    ]
