# Generated by Django 4.1.4 on 2022-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="areaoffice",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KAD", "Kaduna"),
                    ("ZAM", "Zamfara"),
                    ("SOK", "Sokoto"),
                    ("KEB", "Kebbi"),
                ],
                max_length=7,
                verbose_name="state",
            ),
        ),
    ]
