# Generated by Django 4.1.4 on 2022-12-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_band"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="feeder"
                    ),
                ),
                (
                    "kaedco_code",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="kaedco code"
                    ),
                ),
                (
                    "nerc_code",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="nerc code"
                    ),
                ),
                (
                    "voltage_level",
                    models.CharField(
                        choices=[("33", "33KV"), ("11", "11KV")],
                        max_length=4,
                        verbose_name="voltage level",
                    ),
                ),
                (
                    "route_length",
                    models.FloatField(blank=True, verbose_name="route length"),
                ),
                (
                    "conductor_type",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="conductor type",
                    ),
                ),
                (
                    "conductor_cross_sectional_area_m2",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="conductor cross sectional area",
                    ),
                ),
                (
                    "area_office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.areaoffice",
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.band",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=20, null=True, verbose_name="short name"
                    ),
                ),
                (
                    "total_capacity_kva",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total capacity (kva)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DX", "Distribution"), ("TX", "Transmission")],
                        default="DX",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VectorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=6, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerTransformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("make", models.CharField(max_length=50, verbose_name="name")),
                (
                    "capacity_kva",
                    models.PositiveIntegerField(
                        default=0, verbose_name="capacity (kva)"
                    ),
                ),
                (
                    "voltage_ratio",
                    models.CharField(
                        choices=[
                            ("330/132", "330/132KV"),
                            ("132/33", "132/33KV"),
                            ("33/11", "33/11KV"),
                            ("33/0.4", "33/0.4KV"),
                            ("11/0.4", "11/0.4KV"),
                        ],
                        default="33/11",
                        max_length=7,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="serial number",
                    ),
                ),
                ("manufacture_year", models.DateField(blank=True, null=True)),
                ("impedance", models.FloatField(default=0.0, verbose_name="impedance")),
                (
                    "source_feeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.feeder",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.station",
                    ),
                ),
                (
                    "vector_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.vectorgroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "station")},
            },
        ),
        migrations.AddField(
            model_name="feeder",
            name="source_power_transformer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset.powertransformer",
            ),
        ),
        migrations.CreateModel(
            name="DistributionTransformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("make", models.CharField(max_length=50, verbose_name="name")),
                (
                    "capacity_kva",
                    models.PositiveIntegerField(
                        default=0, verbose_name="capacity (kva)"
                    ),
                ),
                (
                    "voltage_ratio",
                    models.CharField(
                        choices=[
                            ("330/132", "330/132KV"),
                            ("132/33", "132/33KV"),
                            ("33/11", "33/11KV"),
                            ("33/0.4", "33/0.4KV"),
                            ("11/0.4", "11/0.4KV"),
                        ],
                        default="33/11",
                        max_length=7,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="serial number",
                    ),
                ),
                ("manufacture_year", models.DateField(blank=True, null=True)),
                ("impedance", models.FloatField(default=0.0, verbose_name="impedance")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="DT Code",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("P", "Public"), ("D", "Dedicated")],
                        default="P",
                        max_length=14,
                        verbose_name="usage",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="latitude",
                    ),
                ),
                ("units", models.SmallIntegerField(verbose_name="Number of Units")),
                (
                    "source_feeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.feeder",
                    ),
                ),
                (
                    "vector_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.vectorgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
