# Generated by Django 4.1.4 on 2022-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="longitude",
            ),
        ),
    ]
