# Generated by Django 4.1.4 on 2022-12-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_station_latitude_station_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="powertransformer",
            name="source_power_transformer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset.powertransformer",
            ),
        ),
    ]
