# Generated by Django 4.1.4 on 2022-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0005_alter_distributiontransformer_make_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeder",
            name="route_length",
            field=models.FloatField(
                blank=True, default=0.0, verbose_name="route length"
            ),
        ),
    ]
