# Generated by Django 4.1.4 on 2022-12-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0006_alter_feeder_route_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powertransformer",
            name="source_power_transformer",
            field=models.ForeignKey(
                blank=True,
                help_text="Fill only for 132KV Transformers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset.powertransformer",
            ),
        ),
    ]
