# Generated by Django 4.1.6 on 2023-02-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0007_alter_powertransformer_source_power_transformer"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="manned",
            field=models.CharField(
                choices=[("Manned", "Manned"), ("Unmanned", "Unmanned")],
                default="Manned",
                max_length=8,
                verbose_name="Manned or Unmanned",
            ),
        ),
        migrations.AlterField(
            model_name="powertransformer",
            name="source_feeder",
            field=models.ForeignKey(
                blank=True,
                help_text="Fill only for 33/11KV Injection Substation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset.feeder",
            ),
        ),
    ]
