# Generated by Django 4.1.6 on 2023-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0008_station_manned_alter_powertransformer_source_feeder"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributiontransformer",
            name="rated_current",
            field=models.CharField(
                blank=True,
                help_text="primary & secondary current written as Ip/Is",
                max_length=20,
                null=True,
                verbose_name="rated current",
            ),
        ),
        migrations.AddField(
            model_name="powertransformer",
            name="rated_current",
            field=models.CharField(
                blank=True,
                help_text="primary & secondary current written as Ip/Is",
                max_length=20,
                null=True,
                verbose_name="rated current",
            ),
        ),
    ]
