# Generated by Django 4.1.6 on 2023-02-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0009_distributiontransformer_rated_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributiontransformer",
            name="rated_current",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="primary & secondary current written as Ip/Is",
                max_length=20,
                null=True,
                verbose_name="rated current",
            ),
        ),
        migrations.AlterField(
            model_name="distributiontransformer",
            name="serial_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="serial number",
            ),
        ),
        migrations.AlterField(
            model_name="powertransformer",
            name="rated_current",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="primary & secondary current written as Ip/Is",
                max_length=20,
                null=True,
                verbose_name="rated current",
            ),
        ),
        migrations.AlterField(
            model_name="powertransformer",
            name="serial_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="serial number",
            ),
        ),
    ]
