# Generated by Django 4.1.6 on 2023-02-16 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("asset", "0010_alter_distributiontransformer_rated_current_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date")),
                (
                    "allocation_mw",
                    models.FloatField(default=0, verbose_name="Allocation (MW)"),
                ),
                (
                    "generation_mw",
                    models.FloatField(default=0, verbose_name="Generation (MW)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN CIRCUIT", "In Circuit"),
                            ("BLACKOUT", "Blackout"),
                        ],
                        default="IN CIRCUIT",
                        max_length=15,
                        verbose_name="grid status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid5,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date")),
                (
                    "load_mw",
                    models.FloatField(blank=True, null=True, verbose_name="load (MW)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN CIRCUIT", "In Circuit"),
                            ("OVER CURRENT", "Overcurrent"),
                            ("EARTH FAULT", "Earth Fault"),
                            ("OVERCURRENT & EARTH FAULT", "Overcurrent & Earth Fault"),
                            ("OUT OF SERVICE", "Out of Service"),
                            ("FREQUENCY CONTROL", "Frequency Control"),
                            ("PLANNED OUTAGE", "Planned Outage"),
                            ("SYSTEM COLLAPSE", "System Collapse"),
                        ],
                        default="IN CIRCUIT",
                        max_length=25,
                        verbose_name="feeder status",
                    ),
                ),
                (
                    "feeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="asset.feeder",
                    ),
                ),
            ],
        ),
    ]
