# Generated by Django 4.1.4 on 2022-12-26 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0007_alter_powertransformer_source_power_transformer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Outage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relay_indication",
                    models.CharField(
                        choices=[
                            ("O/C", "Overcurrent"),
                            ("E/F", "Earth Fault"),
                            ("O/C & E/F", "Overcurrent & Earth Fault"),
                            ("O/S", "Out of Service"),
                            ("F/C", "Frequency Control"),
                            ("P/O", "Planned Outage"),
                        ],
                        max_length=25,
                        verbose_name="relayindication",
                    ),
                ),
                (
                    "load_loss_mw",
                    models.FloatField(default=0.0, verbose_name="load loss in MW"),
                ),
                ("time_out", models.DateTimeField(verbose_name="time out")),
                (
                    "time_in",
                    models.DateTimeField(blank=True, null=True, verbose_name="time in"),
                ),
                (
                    "induced_by",
                    models.CharField(
                        blank=True,
                        choices=[("KAEDCO", "KAEDCO"), ("TCN", "TCN")],
                        max_length=6,
                        null=True,
                        verbose_name="induced by",
                    ),
                ),
                (
                    "fault_cause",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="fault cause",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="resolution",
                    ),
                ),
                (
                    "tcn_staff",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="tcn staff name",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feeder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="asset.feeder"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("time_out", "feeder"),
            },
        ),
    ]
