# Generated by Django 4.1.6 on 2023-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outage",
            options={"ordering": ("-time_out", "feeder")},
        ),
        migrations.AlterField(
            model_name="outage",
            name="fault_cause",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Fault Cause"
            ),
        ),
        migrations.AlterField(
            model_name="outage",
            name="induced_by",
            field=models.CharField(
                blank=True,
                choices=[("KAEDCO", "KAEDCO"), ("TCN", "TCN")],
                max_length=6,
                null=True,
                verbose_name="Induced By",
            ),
        ),
        migrations.AlterField(
            model_name="outage",
            name="load_loss_mw",
            field=models.FloatField(default=0.0, verbose_name="Load Loss(MW)"),
        ),
        migrations.AlterField(
            model_name="outage",
            name="relay_indication",
            field=models.CharField(
                choices=[
                    ("O/C", "Overcurrent"),
                    ("E/F", "Earth Fault"),
                    ("O/C & E/F", "Overcurrent & Earth Fault"),
                    ("O/S", "Out of Service"),
                    ("F/C", "Frequency Control"),
                    ("P/O", "Planned Outage"),
                ],
                max_length=25,
                verbose_name="Relay Indication",
            ),
        ),
        migrations.AlterField(
            model_name="outage",
            name="resolution",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Resolution"
            ),
        ),
        migrations.AlterField(
            model_name="outage",
            name="tcn_staff",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Tcn Staff name"
            ),
        ),
        migrations.AlterField(
            model_name="outage",
            name="time_in",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Time In"),
        ),
        migrations.AlterField(
            model_name="outage",
            name="time_out",
            field=models.DateTimeField(verbose_name="Time Out"),
        ),
    ]
