# Generated by Django 4.1.6 on 2023-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outage", "0002_alter_outage_options_alter_outage_fault_cause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outage",
            name="relay_indication",
            field=models.CharField(
                choices=[
                    ("IN CIRCUIT", "In Circuit"),
                    ("OVER CURRENT", "Overcurrent"),
                    ("EARTH FAULT", "Earth Fault"),
                    ("OVERCURRENT & EARTH FAULT", "Overcurrent & Earth Fault"),
                    ("OUT OF SERVICE", "Out of Service"),
                    ("FREQUENCY CONTROL", "Frequency Control"),
                    ("PLANNED OUTAGE", "Planned Outage"),
                    ("SYSTEM COLLAPSE", "System Collapse"),
                ],
                max_length=25,
                verbose_name="Relay Indication",
            ),
        ),
    ]
